/* Generated by :SkyAssets:skyMaterials. Do not edit by hand. */

/*
 * generated glow fragment shader used by dome66.j3md
 */
#import "Common/ShaderLib/GLSLCompat.glsllib"
uniform vec4 m_ClearGlow;
varying vec2 skyTexCoord;

#ifdef HAS_OBJECT0
        uniform vec4 m_Object0Color;
	uniform sampler2D m_Object0ColorMap;
	varying vec2 object0Coord;
#endif

#ifdef HAS_OBJECT1
        uniform vec4 m_Object1Color;
	uniform sampler2D m_Object1ColorMap;
	varying vec2 object1Coord;
#endif

#ifdef HAS_OBJECT2
        uniform vec4 m_Object2Color;
	uniform sampler2D m_Object2ColorMap;
	varying vec2 object2Coord;
#endif

#ifdef HAS_OBJECT3
        uniform vec4 m_Object3Color;
	uniform sampler2D m_Object3ColorMap;
	varying vec2 object3Coord;
#endif

#ifdef HAS_OBJECT4
        uniform vec4 m_Object4Color;
	uniform sampler2D m_Object4ColorMap;
	varying vec2 object4Coord;
#endif

#ifdef HAS_OBJECT5
        uniform vec4 m_Object5Color;
	uniform sampler2D m_Object5ColorMap;
	varying vec2 object5Coord;
#endif

#ifdef HAS_HAZE
        uniform sampler2D m_HazeAlphaMap;
        uniform vec4 m_HazeGlow;
#endif

#ifdef HAS_CLOUDS0
        uniform sampler2D m_Clouds0AlphaMap;
        uniform vec4 m_Clouds0Glow;
	varying vec2 clouds0Coord;
#endif
#ifdef HAS_CLOUDS0_NORMAL
        uniform sampler2D m_Clouds0NormalMap;
#endif

#ifdef HAS_CLOUDS1
        uniform sampler2D m_Clouds1AlphaMap;
        uniform vec4 m_Clouds1Glow;
	varying vec2 clouds1Coord;
#endif
#ifdef HAS_CLOUDS1_NORMAL
        uniform sampler2D m_Clouds1NormalMap;
#endif

#ifdef HAS_CLOUDS2
        uniform sampler2D m_Clouds2AlphaMap;
        uniform vec4 m_Clouds2Glow;
	varying vec2 clouds2Coord;
#endif
#ifdef HAS_CLOUDS2_NORMAL
        uniform sampler2D m_Clouds2NormalMap;
#endif

#ifdef HAS_CLOUDS3
        uniform sampler2D m_Clouds3AlphaMap;
        uniform vec4 m_Clouds3Glow;
	varying vec2 clouds3Coord;
#endif
#ifdef HAS_CLOUDS3_NORMAL
        uniform sampler2D m_Clouds3NormalMap;
#endif

#ifdef HAS_CLOUDS4
        uniform sampler2D m_Clouds4AlphaMap;
        uniform vec4 m_Clouds4Glow;
	varying vec2 clouds4Coord;
#endif
#ifdef HAS_CLOUDS4_NORMAL
        uniform sampler2D m_Clouds4NormalMap;
#endif

#ifdef HAS_CLOUDS5
        uniform sampler2D m_Clouds5AlphaMap;
        uniform vec4 m_Clouds5Glow;
	varying vec2 clouds5Coord;
#endif
#ifdef HAS_CLOUDS5_NORMAL
        uniform sampler2D m_Clouds5NormalMap;
#endif

vec4 mixColors(vec4 color0, vec4 color1) {
        vec4 result;
        float a0 = color0.a * (1.0 - color1.a);
        result.a = a0 + color1.a;
        if (result.a > 0.0) {
                result.rgb = (a0 * color0.rgb + color1.a * color1.rgb)
                        / result.a;
        } else {
                result.rgb = vec3(0.0);
        }
        return result;
}

void main() {
        vec4 stars = vec4(0.0);
        vec4 objects = vec4(0.0);

        #ifdef HAS_OBJECT0
                if (floor(object0Coord.s) == 0.0 &&
                    floor(object0Coord.t) == 0.0) {
                        vec4 object0 = m_Object0Glow;
                        object0 *= texture2D(m_Object0ColorMap, object0Coord);
                        objects = object0;
                }
	#endif

        #ifdef HAS_OBJECT1
                if (floor(object1Coord.s) == 0.0 &&
                    floor(object1Coord.t) == 0.0) {
                        vec4 object1 = m_Object1Glow;
                        object1 *= texture2D(m_Object1ColorMap, object1Coord);
                        objects = mixColors(objects, object1);
                }
	#endif

        #ifdef HAS_OBJECT2
                if (floor(object2Coord.s) == 0.0 &&
                    floor(object2Coord.t) == 0.0) {
                        vec4 object2 = m_Object2Glow;
                        object2 *= texture2D(m_Object2ColorMap, object2Coord);
                        objects = mixColors(objects, object2);
                }
	#endif

        #ifdef HAS_OBJECT3
                if (floor(object3Coord.s) == 0.0 &&
                    floor(object3Coord.t) == 0.0) {
                        vec4 object3 = m_Object3Glow;
                        object3 *= texture2D(m_Object3ColorMap, object3Coord);
                        objects = mixColors(objects, object3);
                }
	#endif

        #ifdef HAS_OBJECT4
                if (floor(object4Coord.s) == 0.0 &&
                    floor(object4Coord.t) == 0.0) {
                        vec4 object4 = m_Object4Glow;
                        object4 *= texture2D(m_Object4ColorMap, object4Coord);
                        objects = mixColors(objects, object4);
                }
	#endif

        #ifdef HAS_OBJECT5
                if (floor(object5Coord.s) == 0.0 &&
                    floor(object5Coord.t) == 0.0) {
                        vec4 object5 = m_Object5Glow;
                        object5 *= texture2D(m_Object5ColorMap, object5Coord);
                        objects = mixColors(objects, object5);
                }
	#endif

        vec4 color = mixColors(stars, objects);

        vec4 clear = m_ClearGlow;
	#ifdef HAS_HAZE
                vec4 haze = m_HazeGlow;
                haze.a *= texture2D(m_HazeAlphaMap, skyTexCoord).r;
	        clear = mixColors(clear, haze);
	#endif
        color = mixColors(color, clear);
        color.rgb += objects.rgb * objects.a * (1.0 - clear.rgb) * clear.a;

	#ifdef HAS_CLOUDS0
                vec4 clouds0 = m_Clouds0Glow;
		clouds0.a *= texture2D(m_Clouds0AlphaMap, clouds0Coord).r;
		#ifdef HAS_CLOUDS0_NORMAL
			vec3 normal0 = texture2D(m_Clouds0NormalMap, clouds0Coord).xyz;
			normal0 = normal0 * 2.0 - 1.0;
			float relief0 = clamp(0.90 + normal0.z * 0.15, 0.75, 1.15);
			clouds0.rgb *= relief0;
		#endif
                color = mixColors(color, clouds0);
        #endif

	#ifdef HAS_CLOUDS1
                vec4 clouds1 = m_Clouds1Glow;
		clouds1.a *= texture2D(m_Clouds1AlphaMap, clouds1Coord).r;
		#ifdef HAS_CLOUDS1_NORMAL
			vec3 normal1 = texture2D(m_Clouds1NormalMap, clouds1Coord).xyz;
			normal1 = normal1 * 2.0 - 1.0;
			float relief1 = clamp(0.90 + normal1.z * 0.15, 0.75, 1.15);
			clouds1.rgb *= relief1;
		#endif
                color = mixColors(color, clouds1);
        #endif

	#ifdef HAS_CLOUDS2
                vec4 clouds2 = m_Clouds2Glow;
		clouds2.a *= texture2D(m_Clouds2AlphaMap, clouds2Coord).r;
		#ifdef HAS_CLOUDS2_NORMAL
			vec3 normal2 = texture2D(m_Clouds2NormalMap, clouds2Coord).xyz;
			normal2 = normal2 * 2.0 - 1.0;
			float relief2 = clamp(0.90 + normal2.z * 0.15, 0.75, 1.15);
			clouds2.rgb *= relief2;
		#endif
                color = mixColors(color, clouds2);
        #endif

	#ifdef HAS_CLOUDS3
                vec4 clouds3 = m_Clouds3Glow;
		clouds3.a *= texture2D(m_Clouds3AlphaMap, clouds3Coord).r;
		#ifdef HAS_CLOUDS3_NORMAL
			vec3 normal3 = texture2D(m_Clouds3NormalMap, clouds3Coord).xyz;
			normal3 = normal3 * 2.0 - 1.0;
			float relief3 = clamp(0.90 + normal3.z * 0.15, 0.75, 1.15);
			clouds3.rgb *= relief3;
		#endif
                color = mixColors(color, clouds3);
        #endif

	#ifdef HAS_CLOUDS4
                vec4 clouds4 = m_Clouds4Glow;
		clouds4.a *= texture2D(m_Clouds4AlphaMap, clouds4Coord).r;
		#ifdef HAS_CLOUDS4_NORMAL
			vec3 normal4 = texture2D(m_Clouds4NormalMap, clouds4Coord).xyz;
			normal4 = normal4 * 2.0 - 1.0;
			float relief4 = clamp(0.90 + normal4.z * 0.15, 0.75, 1.15);
			clouds4.rgb *= relief4;
		#endif
                color = mixColors(color, clouds4);
        #endif

	#ifdef HAS_CLOUDS5
                vec4 clouds5 = m_Clouds5Glow;
		clouds5.a *= texture2D(m_Clouds5AlphaMap, clouds5Coord).r;
		#ifdef HAS_CLOUDS5_NORMAL
			vec3 normal5 = texture2D(m_Clouds5NormalMap, clouds5Coord).xyz;
			normal5 = normal5 * 2.0 - 1.0;
			float relief5 = clamp(0.90 + normal5.z * 0.15, 0.75, 1.15);
			clouds5.rgb *= relief5;
		#endif
                color = mixColors(color, clouds5);
        #endif

	gl_FragColor = color;
}
