/* Generated by :SkyAssets:skyMaterials. Do not edit by hand. */

/*
 * generated fragment shader used by dome06.j3md
 */
#import "Common/ShaderLib/GLSLCompat.glsllib"
uniform vec4 m_ClearColor;
varying vec2 skyTexCoord;

#ifdef HAS_STARS
        uniform sampler2D m_StarsColorMap;
#endif

#ifdef HAS_HAZE
        uniform sampler2D m_HazeAlphaMap;
        uniform vec4 m_HazeColor;
#endif

#ifdef HAS_CLOUDS0
        uniform sampler2D m_Clouds0AlphaMap;
        uniform vec4 m_Clouds0Color;
	varying vec2 clouds0Coord;
#endif
#ifdef HAS_CLOUDS0_NORMAL
        uniform sampler2D m_Clouds0NormalMap;
#endif

#ifdef HAS_CLOUDS1
        uniform sampler2D m_Clouds1AlphaMap;
        uniform vec4 m_Clouds1Color;
	varying vec2 clouds1Coord;
#endif
#ifdef HAS_CLOUDS1_NORMAL
        uniform sampler2D m_Clouds1NormalMap;
#endif

#ifdef HAS_CLOUDS2
        uniform sampler2D m_Clouds2AlphaMap;
        uniform vec4 m_Clouds2Color;
	varying vec2 clouds2Coord;
#endif
#ifdef HAS_CLOUDS2_NORMAL
        uniform sampler2D m_Clouds2NormalMap;
#endif

#ifdef HAS_CLOUDS3
        uniform sampler2D m_Clouds3AlphaMap;
        uniform vec4 m_Clouds3Color;
	varying vec2 clouds3Coord;
#endif
#ifdef HAS_CLOUDS3_NORMAL
        uniform sampler2D m_Clouds3NormalMap;
#endif

#ifdef HAS_CLOUDS4
        uniform sampler2D m_Clouds4AlphaMap;
        uniform vec4 m_Clouds4Color;
	varying vec2 clouds4Coord;
#endif
#ifdef HAS_CLOUDS4_NORMAL
        uniform sampler2D m_Clouds4NormalMap;
#endif

#ifdef HAS_CLOUDS5
        uniform sampler2D m_Clouds5AlphaMap;
        uniform vec4 m_Clouds5Color;
	varying vec2 clouds5Coord;
#endif
#ifdef HAS_CLOUDS5_NORMAL
        uniform sampler2D m_Clouds5NormalMap;
#endif

vec4 mixColors(vec4 color0, vec4 color1) {
        vec4 result;
        float a0 = color0.a * (1.0 - color1.a);
        result.a = a0 + color1.a;
        if (result.a > 0.0) {
                result.rgb = (a0 * color0.rgb + color1.a * color1.rgb)
                        / result.a;
        } else {
                result.rgb = vec3(0.0);
        }
        return result;
}

void main() {
        #ifdef HAS_STARS
                vec4 stars = texture2D(m_StarsColorMap, skyTexCoord);
        #else
                vec4 stars = vec4(0.0);
        #endif
        vec4 objects = vec4(0.0);

        vec4 color = mixColors(stars, objects);

        vec4 clear = m_ClearColor;
	#ifdef HAS_HAZE
                vec4 haze = m_HazeColor;
                haze.a *= texture2D(m_HazeAlphaMap, skyTexCoord).r;
	        clear = mixColors(clear, haze);
	#endif
        color = mixColors(color, clear);
        color.rgb += objects.rgb * objects.a * (1.0 - clear.rgb) * clear.a;

	#ifdef HAS_CLOUDS0
                vec4 clouds0 = m_Clouds0Color;
		clouds0.a *= texture2D(m_Clouds0AlphaMap, clouds0Coord).r;
		#ifdef HAS_CLOUDS0_NORMAL
			vec3 normal0 = texture2D(m_Clouds0NormalMap, clouds0Coord).xyz;
			normal0 = normal0 * 2.0 - 1.0;
			float relief0 = clamp(0.90 + normal0.z * 0.15, 0.75, 1.15);
			clouds0.rgb *= relief0;
		#endif
                color = mixColors(color, clouds0);
        #endif

	#ifdef HAS_CLOUDS1
                vec4 clouds1 = m_Clouds1Color;
		clouds1.a *= texture2D(m_Clouds1AlphaMap, clouds1Coord).r;
		#ifdef HAS_CLOUDS1_NORMAL
			vec3 normal1 = texture2D(m_Clouds1NormalMap, clouds1Coord).xyz;
			normal1 = normal1 * 2.0 - 1.0;
			float relief1 = clamp(0.90 + normal1.z * 0.15, 0.75, 1.15);
			clouds1.rgb *= relief1;
		#endif
                color = mixColors(color, clouds1);
        #endif

	#ifdef HAS_CLOUDS2
                vec4 clouds2 = m_Clouds2Color;
		clouds2.a *= texture2D(m_Clouds2AlphaMap, clouds2Coord).r;
		#ifdef HAS_CLOUDS2_NORMAL
			vec3 normal2 = texture2D(m_Clouds2NormalMap, clouds2Coord).xyz;
			normal2 = normal2 * 2.0 - 1.0;
			float relief2 = clamp(0.90 + normal2.z * 0.15, 0.75, 1.15);
			clouds2.rgb *= relief2;
		#endif
                color = mixColors(color, clouds2);
        #endif

	#ifdef HAS_CLOUDS3
                vec4 clouds3 = m_Clouds3Color;
		clouds3.a *= texture2D(m_Clouds3AlphaMap, clouds3Coord).r;
		#ifdef HAS_CLOUDS3_NORMAL
			vec3 normal3 = texture2D(m_Clouds3NormalMap, clouds3Coord).xyz;
			normal3 = normal3 * 2.0 - 1.0;
			float relief3 = clamp(0.90 + normal3.z * 0.15, 0.75, 1.15);
			clouds3.rgb *= relief3;
		#endif
                color = mixColors(color, clouds3);
        #endif

	#ifdef HAS_CLOUDS4
                vec4 clouds4 = m_Clouds4Color;
		clouds4.a *= texture2D(m_Clouds4AlphaMap, clouds4Coord).r;
		#ifdef HAS_CLOUDS4_NORMAL
			vec3 normal4 = texture2D(m_Clouds4NormalMap, clouds4Coord).xyz;
			normal4 = normal4 * 2.0 - 1.0;
			float relief4 = clamp(0.90 + normal4.z * 0.15, 0.75, 1.15);
			clouds4.rgb *= relief4;
		#endif
                color = mixColors(color, clouds4);
        #endif

	#ifdef HAS_CLOUDS5
                vec4 clouds5 = m_Clouds5Color;
		clouds5.a *= texture2D(m_Clouds5AlphaMap, clouds5Coord).r;
		#ifdef HAS_CLOUDS5_NORMAL
			vec3 normal5 = texture2D(m_Clouds5NormalMap, clouds5Coord).xyz;
			normal5 = normal5 * 2.0 - 1.0;
			float relief5 = clamp(0.90 + normal5.z * 0.15, 0.75, 1.15);
			clouds5.rgb *= relief5;
		#endif
                color = mixColors(color, clouds5);
        #endif

	gl_FragColor = color;
}
