/* Generated by :SkyAssets:skyMaterials. Do not edit by hand. */

/*
 * generated vertex shader used by dome06.j3md
 */
#import "Common/ShaderLib/GLSLCompat.glsllib"
attribute vec2 inTexCoord;
attribute vec3 inPosition;
uniform mat4 g_WorldViewProjectionMatrix;
uniform vec2 m_TopCoord;
varying vec2 skyTexCoord;

#ifdef HAS_CLOUDS0
        uniform float m_Clouds0Scale;
        uniform vec2 m_Clouds0Offset;
        varying vec2 clouds0Coord;
#endif

#ifdef HAS_CLOUDS1
        uniform float m_Clouds1Scale;
        uniform vec2 m_Clouds1Offset;
        varying vec2 clouds1Coord;
#endif

#ifdef HAS_CLOUDS2
        uniform float m_Clouds2Scale;
        uniform vec2 m_Clouds2Offset;
        varying vec2 clouds2Coord;
#endif

#ifdef HAS_CLOUDS3
        uniform float m_Clouds3Scale;
        uniform vec2 m_Clouds3Offset;
        varying vec2 clouds3Coord;
#endif

#ifdef HAS_CLOUDS4
        uniform float m_Clouds4Scale;
        uniform vec2 m_Clouds4Offset;
        varying vec2 clouds4Coord;
#endif

#ifdef HAS_CLOUDS5
        uniform float m_Clouds5Scale;
        uniform vec2 m_Clouds5Offset;
        varying vec2 clouds5Coord;
#endif

void main(){
        skyTexCoord = inTexCoord;
        /*
         * Keep cloud coordinates consistent with material sampling.
         */
        #ifdef HAS_CLOUDS0
                clouds0Coord = inTexCoord * m_Clouds0Scale + m_Clouds0Offset;
        #endif
        #ifdef HAS_CLOUDS1
                clouds1Coord = inTexCoord * m_Clouds1Scale + m_Clouds1Offset;
        #endif
        #ifdef HAS_CLOUDS2
                clouds2Coord = inTexCoord * m_Clouds2Scale + m_Clouds2Offset;
        #endif
        #ifdef HAS_CLOUDS3
                clouds3Coord = inTexCoord * m_Clouds3Scale + m_Clouds3Offset;
        #endif
        #ifdef HAS_CLOUDS4
                clouds4Coord = inTexCoord * m_Clouds4Scale + m_Clouds4Offset;
        #endif
        #ifdef HAS_CLOUDS5
                clouds5Coord = inTexCoord * m_Clouds5Scale + m_Clouds5Offset;
        #endif

        gl_Position = g_WorldViewProjectionMatrix * vec4(inPosition, 1);
}
